export interface SizeOption {
  size: "Medium" | "Large" | "Standard";
  label: string;
  price: number;
}

export interface MenuItem {
  id: string;
  code?: string;
  name: string;
  category:
    | "pizza"
    | "burger"
    | "wraps"
    | "fries"
    | "deals"
    | "soda"
    | "shakes"
    | "salad"
    | "snacks"
    | "hot"
    | "drinks"
    | "addons";
  description: string;
  price: number;
  sizes?: SizeOption[];
  image: string;
  fallbackImage?: string;
  tag?: string;
  isPopular?: boolean;
  isVeg: boolean;
  quantityNote?: string;
  includes?: string[];
}

export const MENU_CATEGORIES = [
  { id: "all", label: "ALL ITEMS", icon: "✨" },
  { id: "burger", label: "BURGERS", icon: "🍔" },
  { id: "wraps", label: "WRAPS", icon: "🌯" },
  { id: "fries", label: "STARTERS & FRIES", icon: "🍟" },
  { id: "pizza", label: "FRESH BASE PIZZA", icon: "🍕" },
  { id: "deals", label: "DEALS & COMBOS", icon: "🔥" },
  { id: "soda", label: "FRESH SODA", icon: "🍹" },
  { id: "shakes", label: "MILK SHAKES", icon: "🥤" },
  { id: "salad", label: "SALAD", icon: "🥗" },
  { id: "snacks", label: "SNACKS", icon: "🍢" },
  { id: "hot", label: "HOT BEVERAGES", icon: "☕" },
  { id: "drinks", label: "COLD DRINKS", icon: "🍾" },
  { id: "addons", label: "PIZZA ADD-ONS", icon: "🧀" },
] as const;

export const MENU_ITEMS: MenuItem[] = [
  // 1. BURGERS
  {
    id: "b1",
    code: "B1",
    name: "Aloo Tikki Burger",
    category: "burger",
    description: "Crispy seasoned golden potato herb patty, shredded crunchy iceberg lettuce, house secret sauces in a toasted bun.",
    price: 50,
    image: "/menu-burger-aloo-herb.jpg",
    fallbackImage: "/food-burger.jpg",
    isVeg: true,
  },
  {
    id: "b2",
    code: "B2",
    name: "Cheese Burger",
    category: "burger",
    description: "Classic grilled cheeseburger layered with rich melted cheese slice, crisp fresh lettuce, tomato & creamy signature dressing.",
    price: 60,
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-burger.jpg",
    isVeg: true,
  },
  {
    id: "b3",
    code: "B3",
    name: "Crispy Veggie Burger",
    category: "burger",
    description: "Golden crispy vegetable patty packed with farm-fresh garden greens, cheese sauce, tangy relish and toasted brioche bun.",
    price: 80,
    image: "/menu-burger-royal-veg.jpg",
    fallbackImage: "/food-burger.jpg",
    isVeg: true,
  },
  {
    id: "b4",
    code: "B4",
    name: "Crispy Paneer Burger",
    category: "burger",
    description: "Generous crispy fried cottage cheese paneer steak with crisp lettuce, secret tandoori dressing and soft sesame bun.",
    price: 100,
    tag: "BEST SELLER",
    isPopular: true,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/menu-burger-paneer-double.jpg",
    isVeg: true,
  },
  {
    id: "b5",
    code: "B5",
    name: "Bus Special Burger",
    category: "burger",
    description: "Our signature double-decker truck loaded burger with chef's crisp patty, extra cheese, onion rings and signature truck sauces.",
    price: 130,
    tag: "CHEF SPECIAL",
    isPopular: true,
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/menu-burger-paneer-double.jpg",
    isVeg: true,
  },
  {
    id: "b6",
    code: "B6",
    name: "Double Paneer Burger",
    category: "burger",
    description: "Substantial double-stack burger with two thick crispy paneer patties, melted cheddar slices, lettuce and jalapeño mayo.",
    price: 160,
    tag: "SIGNATURE",
    isPopular: true,
    image: "/menu-burger-paneer-double.jpg",
    fallbackImage: "/food-burger.jpg",
    isVeg: true,
  },

  // 2. WRAPS
  {
    id: "w1",
    code: "W1",
    name: "Crispy Paneer Wrap",
    category: "wraps",
    description: "Crispy spiced paneer batons wrapped in a toasted soft tortilla with sliced onions, crunchy capsicum and creamy sauces.",
    price: 130,
    image: "/food-wrap.jpg",
    fallbackImage: "/menu-wrap-paneer-tikka.jpg",
    isVeg: true,
  },
  {
    id: "w2",
    code: "W2",
    name: "Crispy Veggie Wrap",
    category: "wraps",
    description: "Crispy fried vegetable filling with garden-fresh greens, bell peppers and zesty spicy herb mayonnaise inside a toasted wrap.",
    price: 150,
    tag: "BEST SELLER",
    isPopular: true,
    image: "/menu-wrap-mexican-salsa.jpg",
    fallbackImage: "/food-wrap.jpg",
    isVeg: true,
  },
  {
    id: "w3",
    code: "W3",
    name: "Paneer Tikka Wrap",
    category: "wraps",
    description: "Charcoal tandoori marinated paneer tikka, capsicum, pickled onions and aromatic Indian mint chutney wrapped in soft flatbread.",
    price: 190,
    tag: "MUST TRY",
    isPopular: true,
    image: "/menu-wrap-paneer-tikka.jpg",
    fallbackImage: "/food-wrap.jpg",
    isVeg: true,
  },

  // 3. STARTERS (FRIES)
  {
    id: "f1",
    code: "F1",
    name: "French Fries (Salty)",
    category: "fries",
    description: "Classic hot, crispy golden French fries lightly tossed in sea salt.",
    price: 60,
    sizes: [
      { size: "Medium", label: "M (Medium)", price: 60 },
      { size: "Large", label: "L (Large)", price: 80 },
    ],
    image: "/food-fries.jpg",
    fallbackImage: "/menu-fries-peri-peri.jpg",
    isVeg: true,
  },
  {
    id: "f2",
    code: "F2",
    name: "Peri-Peri Fries (Spicy)",
    category: "fries",
    description: "Crispy golden skin-on fries generously coated with fiery, aromatic peri-peri seasoning dust.",
    price: 80,
    isPopular: true,
    sizes: [
      { size: "Medium", label: "M (Medium)", price: 80 },
      { size: "Large", label: "L (Large)", price: 100 },
    ],
    image: "/menu-fries-peri-peri.jpg",
    fallbackImage: "/food-fries.jpg",
    isVeg: true,
  },
  {
    id: "f3",
    code: "F3",
    name: "Cheesy Fries",
    category: "fries",
    description: "Golden crinkle-cut fries smothered in warm molten cheddar cheese sauce and Italian herb sprinkle.",
    price: 100,
    tag: "CROWD FAVORITE",
    isPopular: true,
    sizes: [
      { size: "Medium", label: "M (Medium)", price: 100 },
      { size: "Large", label: "L (Large)", price: 120 },
    ],
    image: "/menu-fries-loaded-cheesy.jpg",
    fallbackImage: "/food-fries.jpg",
    isVeg: true,
  },

  // 4. FRESH BASE PIZZA
  {
    id: "p1",
    code: "P1",
    name: "Margarita Pizza",
    category: "pizza",
    description: "The Classic Italian Pizza With Hot Cheese Topping & Italian Herb Seasoning.",
    price: 180,
    sizes: [
      { size: "Medium", label: "Medium", price: 180 },
      { size: "Large", label: "Large", price: 300 },
    ],
    image: "/menu-pizza-margherita.jpg",
    fallbackImage: "/food-pizza.jpg",
    isVeg: true,
  },
  {
    id: "p2",
    code: "P2",
    name: "Cheese Corn Pizza",
    category: "pizza",
    description: "Hot Cheese, Corn, Best Fragrant With Spices & Herb Crust.",
    price: 230,
    sizes: [
      { size: "Medium", label: "Medium", price: 230 },
      { size: "Large", label: "Large", price: 330 },
    ],
    image: "/images/cheese-corn-pizza.jpg",
    fallbackImage: "/food-pizza.jpg",
    isVeg: true,
  },
  {
    id: "p3",
    code: "P3",
    name: "Mix Veg Lover",
    category: "pizza",
    description: "Loaded Cheese, Onion, Capsicum, Tomato, Olive, Corn on stone-baked crust.",
    price: 300,
    sizes: [
      { size: "Medium", label: "Medium", price: 300 },
      { size: "Large", label: "Large", price: 380 },
    ],
    image: "/food-pizza.jpg",
    fallbackImage: "/menu-pizza-farmhouse.jpg",
    isVeg: true,
  },
  {
    id: "p4",
    code: "P4",
    name: "Chilli Paneer Pizza",
    category: "pizza",
    description: "Masala Paneer, Corn, Green Capsicum with spicy herb sauce and mozzarella.",
    price: 310,
    sizes: [
      { size: "Medium", label: "Medium", price: 310 },
      { size: "Large", label: "Large", price: 390 },
    ],
    image: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/menu-pizza-paneer-makhani.jpg",
    isVeg: true,
  },
  {
    id: "p5",
    code: "P5",
    name: "Butter Paneer Pizza",
    category: "pizza",
    description: "Marinated Chunky Paneer, Onion, Capsicum, Red Paprika with Makhni Sauce.",
    price: 320,
    tag: "BEST SELLER",
    isPopular: true,
    sizes: [
      { size: "Medium", label: "Medium", price: 320 },
      { size: "Large", label: "Large", price: 420 },
    ],
    image: "/menu-pizza-paneer-makhani.jpg",
    fallbackImage: "/food-pizza.jpg",
    isVeg: true,
  },
  {
    id: "p6",
    code: "P6",
    name: "Farm Fresh Pizza",
    category: "pizza",
    description: "Onion, Capsicum, Corn, Jalapeno, Mushroom, Paneer, Tomato & mozzarella.",
    price: 350,
    tag: "CHEF SPECIAL",
    isPopular: true,
    sizes: [
      { size: "Medium", label: "Medium", price: 350 },
      { size: "Large", label: "Large", price: 450 },
    ],
    image: "/menu-pizza-farmhouse.jpg",
    fallbackImage: "/food-pizza.jpg",
    isVeg: true,
  },
  {
    id: "p7",
    code: "P7",
    name: "Our Spl. Pizza",
    category: "pizza",
    description: "Olive, Paneer, Jalapeno, Red Paprika, Mushroom, Tomato, Capsicum, Corn.",
    price: 400,
    tag: "SIGNATURE",
    isPopular: true,
    sizes: [
      { size: "Medium", label: "Medium", price: 400 },
      { size: "Large", label: "Large", price: 500 },
    ],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/menu-pizza-farmhouse.jpg",
    isVeg: true,
  },
  {
    id: "p8",
    code: "P8",
    name: "Super Loaded Pizza",
    category: "pizza",
    description: "Fully Loaded Cheese with Masala Paneer, Olive, Paneer, Jalapeno, Red Paprika, Mushroom, Potato Fries.",
    price: 500,
    tag: "BEST SELLER",
    isPopular: true,
    sizes: [
      { size: "Medium", label: "Medium", price: 500 },
      { size: "Large", label: "Large", price: 600 },
    ],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/menu-pizza-farmhouse.jpg",
    isVeg: true,
  },

  // 5. PIZZA ADD-ONS
  {
    id: "addon-cheese-burst",
    name: "Cheese Burst Crust",
    category: "addons",
    description: "Infuse your pizza crust with molten, velvety liquid cheese that oozes with every single bite.",
    price: 50,
    sizes: [
      { size: "Medium", label: "Medium Crust (+₹50)", price: 50 },
      { size: "Large", label: "Large Crust (+₹80)", price: 80 },
    ],
    image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-pizza.jpg",
    isVeg: true,
  },
  {
    id: "addon-brown-burst",
    name: "Brown Burst Crust",
    category: "addons",
    description: "Crispy roasted whole wheat multi-grain crust burst with secret aromatic savory filling.",
    price: 50,
    sizes: [
      { size: "Medium", label: "Medium Crust (+₹50)", price: 50 },
      { size: "Large", label: "Large Crust (+₹80)", price: 80 },
    ],
    image: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-pizza.jpg",
    isVeg: true,
  },

  // 6. DEALS
  {
    id: "deal-bf",
    code: "BF",
    name: "Budget Friendly Meal",
    category: "deals",
    description: "2 Cheese Burger + Medium Fries + 2 Coke 200ml. The ultimate value road trip companion!",
    price: 190,
    tag: "VALUE MEAL",
    includes: ["2 × Cheese Burger", "1 × Medium French Fries", "2 × Chilled Coke 200ml"],
    image: "https://images.unsplash.com/photo-1610440042657-612c34d95e9f?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/hero-fastfood-feast.jpg",
    isVeg: true,
  },
  {
    id: "deal-pl",
    code: "PL",
    name: "Paneer Lover Combo",
    category: "deals",
    description: "2 Crispy Paneer Burger + Medium Fries + 2 Coke 200ml. Created specifically for authentic cottage cheese connoisseurs.",
    price: 270,
    tag: "BEST SELLER",
    isPopular: true,
    includes: ["2 × Crispy Paneer Burger", "1 × Medium French Fries", "2 × Chilled Coke 200ml"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/hero-fastfood-feast.jpg",
    isVeg: true,
  },
  {
    id: "deal-wm",
    code: "WM",
    name: "Wrap Meal Fiesta",
    category: "deals",
    description: "2 Crispy Paneer Wrap + Medium Fries + 2 Coke 200ml. Rolled fresh with spices, dips and chilled refreshments.",
    price: 330,
    tag: "POPULAR",
    includes: ["2 × Crispy Paneer Wrap", "1 × Medium French Fries", "2 × Chilled Coke 200ml"],
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/hero-fastfood-feast.jpg",
    isVeg: true,
  },
  {
    id: "deal-fl",
    code: "FL",
    name: "Farmer Lover Feast",
    category: "deals",
    description: "1 Farm Fresh Pizza (Medium) + 1 Crispy Paneer Wrap + 2 Coke. Our flagship family feast hot from the food truck oven!",
    price: 490,
    tag: "PARTY DEAL",
    isPopular: true,
    includes: ["1 × Farm Fresh Pizza (Medium)", "1 × Crispy Paneer Wrap", "2 × Chilled Coke"],
    image: "/hero-fastfood-feast.jpg",
    fallbackImage: "/menu-pizza-farmhouse.jpg",
    isVeg: true,
  },

  // 7. FRESH SODA DRINKS
  {
    id: "m1",
    code: "M1",
    name: "Mint Mojito",
    category: "soda",
    description: "Refreshing sparkling soda with fresh crushed garden mint leaves, zesty Persian lime, simple syrup and ice.",
    price: 80,
    tag: "REFRESHER",
    isPopular: true,
    image: "/menu-drink-mint-mojito.jpg",
    fallbackImage: "/food-mojito.jpg",
    isVeg: true,
  },

  // 8. MILK SHAKES
  {
    id: "s1",
    code: "S1",
    name: "Mango Shake",
    category: "shakes",
    description: "Rich and thick tropical milkshake blended with sweet golden Alphonso mangoes, creamy milk and vanilla scoop.",
    price: 100,
    image: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-shake.jpg",
    isVeg: true,
  },
  {
    id: "s2",
    code: "S2",
    name: "Chocolate Shake",
    category: "shakes",
    description: "Decadent dark Belgian chocolate sauce churned thick with chilled whole milk and chocolate curls on top.",
    price: 100,
    tag: "BESTSELLER",
    isPopular: true,
    image: "/menu-shake-belgian-chocolate.jpg",
    fallbackImage: "/food-shake.jpg",
    isVeg: true,
  },
  {
    id: "s3",
    code: "S3",
    name: "Strawberry Shake",
    category: "shakes",
    description: "Velvety sweet strawberry milkshake made with real strawberry crush, whipped cream and a cherry swirl.",
    price: 100,
    image: "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-shake.jpg",
    isVeg: true,
  },
  {
    id: "s4",
    code: "S4",
    name: "Cold Coffee",
    category: "shakes",
    description: "Smooth, velvety cold-brewed espresso blended with chilled milk and ice cream. The classic highway energizer.",
    price: 100,
    isPopular: true,
    image: "/menu-shake-cold-coffee.jpg",
    fallbackImage: "/food-shake.jpg",
    isVeg: true,
  },
  {
    id: "s5",
    code: "S5",
    name: "Butter Scotch Shake",
    category: "shakes",
    description: "Rich butterscotch milkshake infused with buttery caramel sauce and crispy praline butterscotch bits.",
    price: 120,
    tag: "BEST SELLER",
    isPopular: true,
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-shake.jpg",
    isVeg: true,
  },
  {
    id: "s6",
    code: "S6",
    name: "Oreo Shake",
    category: "shakes",
    description: "Ultra-thick milkshake blended with crunchy chocolate Oreo cookies, topped with whipped cream and crushed Oreos.",
    price: 120,
    tag: "POPULAR",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-shake.jpg",
    isVeg: true,
  },

  // 9. SALAD
  {
    id: "sd1",
    code: "SD1",
    name: "Paneer Tikka Salad",
    category: "salad",
    description: "Fresh healthy bowl loaded with charcoal grilled paneer tikka, crisp lettuce, cucumber, tomatoes, bell peppers and lemon herb dressing.",
    price: 160,
    tag: "HEALTHY CRUNCH",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-paneer.jpg",
    isVeg: true,
  },

  // 10. SNACKS
  {
    id: "gm1",
    code: "GM1",
    name: "Golden Mushroom",
    category: "snacks",
    description: "Crispy golden crumb-fried juicy button mushrooms seasoned with Punjabi spices, served steaming hot.",
    price: 90,
    image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-bread.jpg",
    isVeg: true,
  },
  {
    id: "pf2",
    code: "PF2",
    name: "Paneer Finger",
    category: "snacks",
    description: "6 pieces of succulent spiced cottage cheese fingers coated in golden crunchy batter, served with house special dip.",
    price: 90,
    tag: "BEST SELLER",
    isPopular: true,
    quantityNote: "6 pcs",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-paneer.jpg",
    isVeg: true,
  },
  {
    id: "dip-sauce",
    name: "Any Dip Sauce",
    category: "snacks",
    description: "Your choice of rich creamy dipping sauce: Cheesy Jalapeño, Tandoori Garlic Dip, or Spicy Chipotle Dip.",
    price: 30,
    image: "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-fries.jpg",
    isVeg: true,
  },

  // 11. HOT BEVERAGES
  {
    id: "c1",
    code: "C1",
    name: "Spl. Kadak Chai",
    category: "hot",
    description: "Traditional highway kadak tea brewed rich with fresh grated ginger, crushed green cardamom and mountain spices.",
    price: 20,
    tag: "BEST SELLER",
    isPopular: true,
    image: "/menu-drink-kulhad-chai.jpg",
    fallbackImage: "/menu-drink-kulhad-chai.jpg",
    isVeg: true,
  },
  {
    id: "c2",
    code: "C2",
    name: "Coffee",
    category: "hot",
    description: "Hot, creamy, frothed cafe-style coffee prepared fresh with aromatic roasted coffee beans and whole milk.",
    price: 40,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/menu-drink-kulhad-chai.jpg",
    isVeg: true,
  },

  // 12. COLD DRINKS / BOTTLED BEVERAGES
  {
    id: "cold-drinks",
    name: "Cold Drinks / Bottled Beverages",
    category: "drinks",
    description: "Selection of chilled canned/bottled cold drinks (Coca-Cola, Thums Up, Sprite, Fanta, Diet Coke, and Chilled Mineral Water).",
    price: 25,
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80",
    fallbackImage: "/food-mojito.jpg",
    isVeg: true,
  },
];

export const TRUCK_HOTSPOTS = [
  {
    id: "top-deck",
    title: "Double-Decker Rooftop Glass Lounge",
    tag: "Rooftop Experience",
    position: { top: "18%", left: "32%" },
    category: "Eat Good · Travel Far · Repeat",
    description:
      "Our signature climate-controlled glass upper deck with authentic thatched bamboo ceiling and warm Edison filament lamps. Enjoy panoramic views of Grand Trunk Road with friends and family.",
    highlightImage: "/rooftop-dining.jpg",
    buttonLabel: "Explore Ambience",
  },
  {
    id: "burger-sign",
    title: "Good Food Happier People",
    tag: "Brand Signboard",
    position: { top: "12%", left: "74%" },
    category: "Burgers & Fries",
    description:
      "Our signature illuminated rooftop billboard displaying our pure vegetarian burger & crispy golden fries. 'Good Food Happier People' is our daily promise.",
    highlightImage: "/menu-burger-paneer-double.jpg",
    buttonLabel: "View Burgers",
  },
  {
    id: "logo-badge",
    title: "Glowing Chef Mascot Badge",
    tag: "Authentic Identity",
    position: { top: "48%", left: "59%" },
    category: "Ghumans Kitchen Express",
    description:
      "The illuminated circular badge of Chef Ghuman holding the golden pizza slice. Pure vegetarian culinary excellence on wheels.",
    highlightImage: "/ghumans-truck.jpg",
    buttonLabel: "Our Story",
  },
  {
    id: "pizza-window",
    title: "Live Stone-Baked Pizza Oven",
    tag: "Window 01",
    position: { top: "52%", left: "71%" },
    category: "Artisan Pizzas",
    description:
      "Watch your pizza being freshly hand-tossed and baked at over 350°C right before your eyes with molten mozzarella and fresh veggies.",
    highlightImage: "/menu-pizza-farmhouse.jpg",
    buttonLabel: "View Pizzas",
  },
  {
    id: "wraps-counter",
    title: "Tandoori Wraps & Rolls Station",
    tag: "Window 02",
    position: { top: "53%", left: "80%" },
    category: "Wraps & Kebabs",
    description:
      "Freshly rolled parathas stuffed with sizzling marinated paneer tikka, spicy mint chutney and crisp garden onions.",
    highlightImage: "/menu-wrap-paneer-tikka.jpg",
    buttonLabel: "View Wraps",
  },
  {
    id: "shakes-bar",
    title: "Chilled Shakes & Mint Mojito Bar",
    tag: "Window 03",
    position: { top: "55%", left: "87%" },
    category: "Beverages",
    description:
      "Ice-cold Belgian shakes, thick cold coffee frappes and fizzy refreshing mint mojitos crafted on-the-spot.",
    highlightImage: "/menu-drink-mint-mojito.jpg",
    buttonLabel: "View Shakes",
  },
];
